version: "3"

services:
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend
            - mongo
        links:
            - backend
    backend:
      build: ./backend
      depends_on:
        - mongo
      links:
        - mongo
    mongo:
      image: mongo
      volumes:
        - ./db:/data/db
   
  